version: '3'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    # environment:
    #   - MYSQL_HOST=$MYSQL_HOST
    #   - MYSQL_USER=$MYSQL_USER
    #   - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
    #   - MYSQL_DATABASE=$MYSQL_DATABASE
    #   - MYSQL_PORT=$MYSQL_PORT
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
  nginx:
    build: ./nginx
    ports:
      - 80:80
volumes:
  mysql-data: